### PR TITLE
re-enable event tap when it's disabled by timeout

### PR DESCRIPTION
**Pull request by wwwjfy**

### CODE REVIEW

**Comment by wwwjfy** [comment]
Sometimes I met the situation that when my laptop woke up or unlocked from screen sleep, the modifier + click (e.g. cmd + click in Safari to open a link in a new tab) didn't work.

After investigation, I saw event `kCGEventTapDisabledByTimeout` was received. So I think re-enabling it is a good idea before we find out why it happens.

**Comment by tekezo** [comment]
Thanks!

**Comment by lornally** [comment]
hi, guru


I have known your email address from https://github.com/tekezo <https://github.com/tekezo>, 
nice to meet you, i'd like to appreciate your time reading this letter.
 

I m writig to ask  two  question, that has already perplexed me for a long time :
1. where can i find the dvorak keymap json for karabiner-elements.
2. how do i configure that ignore mac inner keyboard on karabiner-elements,  just like it in karabiner.



Thank you very much for your time. I am looking forward to hearing from you. 


best regards

machangkun

**Comment by wwwjfy** [comment]
@lornally This is not a forum, so if you have questions, you'd better go to https://github.com/tekezo/Karabiner-Elements/issues to search any thing already asked/requested, and if not, you can create a new issue.
A issue/PR (or thread) should focus on one thing

**Pull request merged**
