### PR TITLE
Enabled eject key for simple modifications

### PR DESCRIPTION
**Pull request by PierBover**
As instructed by @gemedet here:

https://github.com/tekezo/Karabiner-Elements/issues/46#issuecomment-361102355

### CODE REVIEW

**Comment by gemedet** [comment]
Haven't tested, but I think we want it to be similar to `volume_increment` above it:
```
    {
        "label": "eject",
        "data": {
            "consumer_key_code": "eject"
        }
    }
```

**Comment by PierBover** [comment]
Makes sense that it would follow the same format. This is what I have in the downloaded app and works:

```
    {
        "name": "volume_increment",
        "type": "consumer_key_code"
    },
    {
        "name": "eject",
        "type": "consumer_key_code"
    }
```

**Comment by tekezo** [comment]
Unfortunately, Karabiner-Elements cannot modify the eject key due to the limitation of macOS API.
(We should not remove `"not_from": true`.)

**Comment by PierBover** [comment]
But it works...

**Comment by tekezo** [comment]
I'm sorry, it works on Magic Keyboard.
(I misunderstood since I confirmed with Apple Wired Keyboard which is not able to change the eject key.)

I've add the eject key into Simple Modifications at v11.5.4.
Please confirm the latest beta version.

Check for beta updates

**Comment by PierBover** [comment]
@tekezo it works.

Since I had previously hacked `simple_modifications.json` I had to deselect and reselect the `eject` key for it to work.

**Comment by nicexe** [comment]
It doesn't seem to work for me on CODE Keyboard. I tried mapping eject to 'a' for example but it doesn't work. Event Viewer seems to be picking eject up though.

screen shot 2018-02-06 at 11 39 09 am

**Comment by PierBover** [comment]
@nicexe these WASD keyboards have something weird going on. My wife has one and she hasn't been able to properly map all keys either.

**Comment by nicexe** [comment]
@PierBover I don't think thats the case. I was able to map everything using the same exact keyboard when I was on osx 10.10 using a slightly older version of Karabiner (not elements)

**Pull request closed without merging**
