### PR TITLE
`set_inputsource` to change current input source

### PR DESCRIPTION
**Pull request by dstd**
Added `set_inputsource` event, with value should contain input source id, like `com.apple.keylayout.US`

Example of usage:
```js
{
    "title": "Input source selection",
    "rules": [{
        "description": "Cmd_L for US, Cmd_R for RU, if pressed alone",
        "manipulators": [{
            "type": "basic",
            "from": {
                "key_code": "left_command",
                "modifiers": {"optional": ["any"]}
            },
            "to": [{"key_code": "left_command"}],
            "to_if_alone": [{"set_inputsource": "com.apple.keylayout.US"}]
        }, {
            "type": "basic",
            "from": {
                "key_code": "right_command",
                "modifiers": {"optional": ["any"]}
            },
            "to": [{"key_code": "right_command"}],
            "to_if_alone": [{"set_inputsource": "com.apple.keylayout.RussianWin"}]
        }]
    }]
}
```

### CODE REVIEW

**Comment by tekezo** [comment]
Thank you for feedback!

I think it's better to use shell_command. How about this?
https://github.com/tekezo/Karabiner-Elements/issues/994

**Comment by dstd** [comment]
Yeah, I tried this one before put my hands into the code 🙂 IMHO it's not quite responsive – barely noticeable delays, but annoying at daily use, especially when the Mac is under a heavy load.

And actually it's a part one of my reimplementation of features of original Karabiner which got into my habbit. Second one is for temporal switch of the input source while CapsLock is pressed and switch back when released [pushed into [dstd/feature-inputsource](https://github.com/dstd/Karabiner-Elements/commits/feature-inputsource) branch]:
```
{
    "description": "Swap input source while CapsLock being held",
    "manipulators": [{
        "type": "basic",
        "conditions": [{"type": "inputsource_if", "id": "com.apple.keylayout.US"}],
        "from": {
            "key_code": "caps_lock",
            "modifiers": {"optional": ["any"]}
        },
        "to": [{"set_inputsource": "com.apple.keylayout.RussianWin"}],
        "to_after_key_up": [{"set_inputsource": "com.apple.keylayout.US"}]
    }, {
        "type": "basic",
        "conditions": [{"type": "inputsource_if", "id": "com.apple.keylayout.RussianWin"}],
        "from": {
            "key_code": "caps_lock",
            "modifiers": {"optional": ["any"]}
        },
        "to": [{"set_inputsource": "com.apple.keylayout.US"}],
        "to_after_key_up": [{"set_inputsource": "com.apple.keylayout.RussianWin"}]
    }]
}
```

**Comment by dstd** [comment]
Anyway it's ok if you don't want these features in main repo. Thanks for the app!

**Comment by torchello** [comment]
@dstd Thank you for the efforts. Works like a charm! Using your branch and happy with language switch after a long break 👍

**Comment by tekezo** [comment]
I merged with some changes!
`select_input_source` is available since Karabiner-Elements 11.1.9. (the latest beta version)

* `set_inputsource` -> `select_input_source`
* Specify input source with `language`, `input_source_id` or `input_mode_id`. 
* Example: https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/example_select_input_source.json

**Pull request closed without merging**
