### PR TITLE
Improve documentation to help starters

### PR DESCRIPTION
**Pull request by talha131**
In view of questions like these, the usage document should be improved.

https://github.com/tekezo/Karabiner-Elements/issues/77#issuecomment-249100893
https://github.com/tekezo/Karabiner-Elements/issues/88

There are several other issues where users are confused on how to kick start karabiner configuration.

This patch, describes

1. How and where to create karabiner.json
2. Basic introduction to the format of karabiner.json
3. Explanation to what are key codes
4. Remove `curl` examples to keep it simple.
5. It adds an example of mapping menu key to option key.

### CODE REVIEW

**Comment by sunapi386** [comment]
These commits should probably be squashed to one, having too small of changes per commit and all commits revolve around one topic.

**Comment by vladimirbebeshko** [comment]
From the user point of view these are very helpful changes! @talha131 thanks a lot!

**Comment by talha131** [comment]
@sunapi386 I agree in principle. The reason I kept the separate is if @tekezo dislikes any commit he can cherry pick the rest.

**Comment by tekezo** [comment]
Thanks!

**Pull request merged**
