### PR TITLE
set keyboard_type (ansi, iso, jis) function implemented.

### PR DESCRIPTION
**Pull request by dcato**
Hello Mr. takezo,

Thank you for your very convenient tool. I'm using your tool since KeyRemap4MacBook.

 I encountered a problem that my JIS keyboard wrongly recognized as ANSI keyboard. I was using this keyboard with Karabiner's `__SetKeyboardType__ KeyboardType::JIS_MACBOOK_2008` option. So I implemented almost same function on Karabiner-Element, and I confirmed it works in my case.

 It seems keyboard layout problem is common, so I think this modification may be useful for other people too. If you think this modification is appropriate, please merge this into your source tree.

- Modified Preferences App
image

- karabiner.json
image

- probably related issues
  - JIS external keyboard recognized as US (ASCII) keyboard after v0.90.47 #278
  - Built-in and external keyboard differs #229
  - Wrong keyboard layout used (english, instead of german) #323

Thank you,

### CODE REVIEW

**Comment by yishanhome** [comment]
Thank you very much

**Comment by tekezo** [comment]
Thanks!
I'll check your changes and include it to next release.

**Comment by tekezo** [comment]
I've merged this changes at Karabiner-Elements v0.90.61.

**Comment by dcato** [comment]
Sorry for my late reply.

Thank you for your work for merging. New icons are cute and space-saving.
I'm glad that my code merged to such a great tool.

Thank you,

**Pull request merged**
