### PR TITLE
Add example to change caps lock to F19

### PR DESCRIPTION
**Pull request by vova**
(for those who used CapsLock as keyboard layout switcher with old Karabiner+Seil)

### CODE REVIEW

**Comment by nomaed** [comment]
@vova I remapped my CTRL key but I have no idea how to cause macOS Sierra to actually use this key to switch the layouts, since Seil no longer works. How did you manage to do that?

**Comment by vova** [comment]
Hi Boris,  

Simply remap your CTRL key to F19 (or any other “major” Fnumber), with the config file similar to mine (for CapsLock), then open the mac os system preferences => keyboard => shortcuts and set F19 as a hotkey for input source switcher: https://cl.ly/112G1Y021X1F/Image%202016-09-21%20at%2018.45.57.png

Best,


--  
Vova

**Comment by nomaed** [comment]
Hi Vova,

Just after writing this message, I went to keyboard preferences and did exactly that. I don’t know why I didn’t try it before. I was confused :)
Anyhow, after doing that I removed my original message since it was no longer relevant, but maybe it should remain here for anyone who is as confused as myself ;)

Thanks,
Boris.

**Comment by alex-ketch** [comment]
You might not need Karabiner for this anymore, as it's somewhat built into macOS 10.12

screen shot 2016-09-22 at 00 17 04

**Comment by vova** [comment]
Hi Alex, 

that option is toking promising, through I don’t see it in my input sources settings, maybe because I use “ABC Extended” instead of “U.S.” keyboard layout. What are the layouts you use?

**Comment by tekezo** [comment]
Thanks!

**Comment by nomaed** [comment]
@vova I tried with `ABC` and `ABC Extended`, I have the option:
However, I tried with various settings, but it just won't toggle between the 2 layouts I have (`ABC` & `Hebrew`)

screen shot 2016-09-22 at 13 04 00

**Comment by vova** [comment]
@nomaed, @alex-ketch would you mind to show the left part of the settings you have? I’ve tried with different language pairs (like US vs. Russian, both are from the MacOS package), with no luck: there is no option “Use Caps Lock” in my settings: settings

and I have Sierra 10.12 (16A323)

**Comment by nomaed** [comment]
Updated to 10.12 (16A323) yesterday.

screen shot 2016-09-22 at 16 26 50

**Comment by alex-ketch** [comment]
@vova Hello neighbour!
The setting is visible with the system default Georgian layout, but I'm sorry to say I tried with Russian layout and the setting disappeared :(

screen shot 2016-09-22 at 10 24 18
screen shot 2016-09-22 at 10 26 42

**Comment by nomaed** [comment]
@vova Just for the heck of it, I tried with 3 layouts and the option is the same. I don't know what's so special in `ABC` (and what's the difference between it and `US`), and I had option

screen shot 2016-09-22 at 16 28 35

Then I removed the Hebrew to leave on ABC and Russian, and as @alex-ketch noted, the option disappeared altogether. Жопа.

**Comment by vova** [comment]
@nomaed @alex-ketch thank you both a lot for your screenshots and clarification. Really strange behaviour, so I still make use of Karabiner-Elements :)

**Pull request merged**
