### PR TITLE
rebuild script

### PR DESCRIPTION
**Pull request by axet**
simple rebuild script. I can make it part of Makefile if you ask.

### CODE REVIEW

**Comment by tekezo** [comment]
Thanks!
I made some changes and move to `scripts/build-and-install.sh`.

/https://github.com/tekezo/Karabiner-Elements/blob/master/scripts/build-and-install.sh

**Comment by axet** [comment]
Lovely! Very helping project! Nice job!

**Comment by axet** [comment]
Since you moved this script to /scripts it makes sance do not 'git pull --rebase' and work for current commit.

**Comment by tekezo** [comment]
The changed script moves the current directory in here.
https://github.com/tekezo/Karabiner-Elements/blob/master/scripts/build-and-install.sh#L3-L4

Please update git once by hand to update build-and-install.sh and then execute build-and-install.sh.

**Pull request merged**
